<?php

/**
 * Implements hook_permission().
 */
function dsm_param_permission() {
  return array(
    'administer parameter message' => array(
      'title' => t('Administer the Parameter Message module.'),
      'description' => t('Perform administration tasks on the Parameter Message module.'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function dsm_param_menu() {
  $items['admin/config/dsm_param'] = array(
    'title' => 'Parameter Message',
    'description' => 'Manage the Parameter Message module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dsm_param_admin'),
    'access arguments' => array('administer parameter message'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dsm_param.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function dsm_param_init() {
  $target_param = variable_get('dsm_param_parameter_name', NULL);
  if (!empty($target_param) && !empty($_GET[$target_param])) {
    drupal_set_message(check_plain($_GET[$target_param]));
  }
}
